# frozen_string_literal: true

source 'https://rubygems.org'

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'benchmark', '~> 0.2.0'
gem 'nokogiri', '~> 1.13.8'
gem 'byebug', '~> 11.1.3'
